<?php

class Language {

	private static $supported_langs = array(
		"Deutsch" => "de",
		"English" => "en",
		//"Español" => "es",
		"Français" => "fr",
		"Italiano" => "it",
		//"Português (Brasil)" => "pt-br",
		"日本語" => "ja"
	);

	public static function get_languages() {
		return self::$supported_langs;
	}

	public static function best() {
		if(!isset($_SERVER['HTTP_ACCEPT_LANGUAGE'])) {
			return 'en';
		}
		$languages = explode(',', $_SERVER['HTTP_ACCEPT_LANGUAGE']);
		foreach($languages as $lang) {
			$break = explode(';', $lang);
			$lang = $break[0];
			if(in_array($lang, self::$supported_langs)) {
				return $lang;
			}
		}
		return 'en';
	}

	public static function get($language, $string) {
		if (array_key_exists($language, self::$translation) && array_key_exists($string, self::$translation[$language])) {
			return self::$translation[$language][$string];
		} elseif (array_key_exists($string, self::$translation['en'])) {
			return self::$translation['en'][$string];
		} else {
			return $string;
		}
	}

	public static function exists($language) {
		if (in_array($language, self::$supported_langs)) {
			return true;
		} else {
			return false;
		}
	}

	public static function get_missing($language) {
		if (array_key_exists($language, self::$translation)) {
			$result = array();
			foreach(self::$translation['en'] as $key => $string) {
				if (!array_key_exists($key, self::$translation[$language])) {
					array_push($result, array($key => $string));
				}
			}
			return $result;
		} else {
			return null;
		}
	}

	public static $translation = array(
		"en" => array(
			"site_name" => "Dinklebot",
			"site_description" => "Your personal companion for tracking and showing your Guardians",
			"site_styled_description" => "Your <i>personal companion</i> for <strong>tracking</strong> and <strong>showing</strong> your Guardians",
			"site_username" => "Username",
			"site_footer_contact" => "For feedback, suggestions, bug reports or anything related with this website, contact us on <a href='https://www.facebook.com/dinklebotapp'>Facebook</a> or <a href='http://redd.it/33aizq'>Reddit</a>!",
			"site_footer_mention" => "is in no way affiliated with Bungie.",
			"site_footer_language" => "Language",
			"site_thankyou" => "Thank you a lot!",
			"site_thankyou_f" => "You're what makes this website awesome!",
			"category_exotic_armor" => "Exotic Armor",
			"category_exotic_weapons" => "Exotic Weapons",
			"category_vog_armor" => "Vault of Glass Armor",
			"category_vog_weapons" => "Vault of Glass Weapons",
			"category_vog_misc" => "Vault of Glass Misc",
			"category_crota_armor" => "Crota's End Armor",
			"category_crota_weapons" => "Crota's End Weapons",
			"category_crota_misc" => "Crota's End Misc",
			"category_ironbanner_armor" => "Iron Banner Armor",
			"category_ironbanner_weapons" => "Iron Banner Weapons",
			"category_ironbanner_misc" => "Iron Banner Misc",
			"info_obtained" => "Obtained",
			"info_refresh" => "This information refreshes every hour.",
			"info_ends" => "Ends ",
			"info_ends_f" => "",
			"info_modifiers" => "Modifiers",
			"info_rewards" => "Possible Rewards",
			"info_completed" => "Completed",
			"info_completed_b" => "Completed ",
			"info_completed_f" => "",
			"info_completions" => "Completions",
			"info_light_twenty" => "You must be level 20 to gain Light.",
			"info_no_pvp" => "You must participate in the Crucible at least once to obtain medals.",
			"time_played" => "Played ",
			"time_played_f" => "",
			"time_active" => "Active",
			"time_minute" => "m ",
			"time_hour" => "h ",
			"time_day" => "d ",
			"button_share" => "Share",
			"button_permalink" => "Permalink",
			"button_reload" => "Reload",
			"button_characters" => "Guardians",
			"button_grimoire" => "Grimoire",
			"button_collection" => "Collection",
			"button_show" => "Show",
			"menu_overview" => "Guardian",
			"menu_weekly" => "Periodic",
			"menu_equipment" => "Equipment",
			"menu_progression" => "Progression",
			"menu_statistics" => "Statistics",
			"menu_medals" => "Medals",
			"menu_all" => "All",
			"menu_story" => "Story",
			"menu_patrol" => "Patrol",
			"menu_strikes" => "Strike",
			"menu_crucible" => "Crucible",
			"menu_raid" => "Raid",
			"playstation_exclusive" => "Playstation Exclusive",
			"vog_exclusive" => "Vault of Glass Exclusive",
			"crota_exclusive" => "Crota's End Exclusive",
			"iron_exclusive" => "Iron Banner Exclusive",
			"character_prestige" => "Mote of Light",
			"destination_chests_cosmodrome" => "Earth Golden Chests",
			"destination_chests_mars" => "Mars Golden Chests",
			"destination_chests_moon" => "Moon Golden Chests",
			"destination_chests_venus" => "Venus Golden Chests",
			"faction_cryptarch" => "Crypto-Archeology",
			"faction_eris" => "Crota's Bane",
			"faction_event_iron_banner" => "Iron Banner",
			"faction_event_queen" => "Queen",
			"faction_fotc_vanguard" => "Vanguard Reputation",
			"faction_pvp" => "The Crucible",
			"faction_pvp_dead_orbit" => "Dead Orbit",
			"faction_pvp_future_war_cult" => "Future War Cult",
			"faction_pvp_new_monarchy" => "New Monarchy",
			"pvp_iron_banner.loss_tokens" => "Medallions of Iron",
			"pve_coins" => "Vanguard Marks",
			"pvp_coins" => "Crucible Marks",
			"weekly_pve" => "Weekly Vanguard Marks",
			"weekly_pvp" => "Weekly Crucible Marks",
			"medal_value" => "Value",
		),
		"fr" => array(
			"site_name" => "Dinklebot",
			"site_description" => "Votre compagnion personnel pour suivre et montrer vos Gardiens",
			"site_styled_description" => "Votre <i>compagnion personnel</i> pour <strong>suivre</strong> et <strong>montrer</strong> vos Gardiens",
			"site_username" => "Nom d'utilisateur",
			"site_footer_contact" => "Pour des commentaires, suggestions, rapports de bogues ou quoi que ce soit en lien avec ce site, contactez-nous sur <a href='https://www.facebook.com/dinklebotapp'>Facebook</a> ou <a href='http://redd.it/33aizq'>Reddit</a>!",
			"site_footer_mention" => "n'est aucunement affilié à Bungie.",
			"site_footer_language" => "Langue",
			"site_thankyou" => "Merci beaucoup!",
			"site_thankyou_f" => "Vous êtes ce qui rend ce site extraordinaire!",
			"category_exotic_armor" => "Armures exotiques",
			"category_exotic_weapons" => "Armes exotiques",
			"category_vog_armor" => "Armures du Caveau de Verre",
			"category_vog_weapons" => "Armes du Caveau de Verre",
			"category_vog_misc" => "Caveau de Verre (misc.)",
			"category_crota_armor" => "Armures de La chute de Cropta",
			"category_crota_weapons" => "Armes de La chute de Cropta",
			"category_crota_misc" => "La chute de Cropta (misc.)",
			"category_ironbanner_armor" => "Armures de La bannière de Fer",
			"category_ironbanner_weapons" => "Armes de La bannière de Fer",
			"category_ironbanner_misc" => "La bannière de Fer (misc.)",
			"info_obtained" => "Obtenu",
			"info_refresh" => "Ces informations sont mises à jour toutes les heures.",
			"info_ends" => "Termine ",
			"info_ends_f" => "",
			"info_modifiers" => "Modificateurs",
			"info_rewards" => "Récompenses possibles",
			"info_completed" => "Complété",
			"info_completed_b" => "Complété ",
			"info_completed_f" => "",
			"info_completions" => "Complétions",
			"info_light_twenty" => "Vous devez être niveau 20 pour obtenir de la Lumière.",
			"info_no_pvp" => "Vous devez participer à L'Épreuve au moins une fois pour obtenir des médailles.",
			"time_played" => "A joué ",
			"time_played_f" => "",
			"time_active" => "Actif",
			"time_minute" => " min ",
			"time_hour" => " h ",
			"time_day" => " j ",
			"button_share" => "Partager",
			"button_permalink" => "Permalien",
			"button_reload" => "Mettre à jour",
			"button_characters" => "Gardiens",
			"button_groimoire" => "Grimoire",
			"button_collection" => "Collection",
			"button_show" => "Afficher",
			"menu_overview" => "Gardien",
			"menu_weekly" => "Périodique",
			"menu_equipment" => "Équipement",
			"menu_progression" => "Progression",
			"menu_statistics" => "Statistiques",
			"menu_medals" => "Médailles",
			"menu_all" => "Tous",
			"menu_story" => "Histoire",
			"menu_patrol" => "Patrouille",
			"menu_strikes" => "Assaut",
			"menu_crucible" => "L'Épreuve",
			"menu_raid" => "Raid",
			"playstation_exclusive" => "Exclusivité Playstation",
			"vog_exclusive" => "Exclusivité du Caveau de Verre",
			"crota_exclusive" => "Exclusivité de La chute de Cropta",
			"iron_exclusive" => "Exclusivité de La bannière de Fer",
			"character_prestige" => "Particule de Lumière",
			"destination_chests_cosmodrome" => "Coffres dorés de la Terre",
			"destination_chests_mars" => "Coffres dorés de Mars",
			"destination_chests_moon" => "Coffres dorés de la Lune",
			"destination_chests_venus" => "Coffres dorés de Vénus",
			"faction_cryptarch" => "Cryptoarchéologie",
			"faction_eris" => "Le Fléau de Cropta",
			"faction_event_iron_banner" => "Bannière de Fer",
			"faction_event_queen" => "Reine",
			"faction_fotc_vanguard" => "Estime de l'Avant-Garde",
			"faction_pvp" => "L'Épreuve",
			"faction_pvp_dead_orbit" => "L'Astre Mort",
			"faction_pvp_future_war_cult" => "Culte de la Guerre Future",
			"faction_pvp_new_monarchy" => "Nouvelle Monarchie",
			"pvp_iron_banner.loss_tokens" => "Médallions de Fer",
			"pve_coins" => "Estime de l'Avant-Garde",
			"pvp_coins" => "Estime de l'Épreuve",
			"weekly_pve" => "Estime de l'Avant-Garde hebdomadaire",
			"weekly_pvp" => "Estime de l'Épreuve hebdomadaire",
			"medal_value" => "Valeur",
		),
		"de" => array(
			"info_refresh" => "Diese Informationen jede Stunde actualizieren.",
			"info_ends" => "Enden ",
			"info_ends_f" => "",
			"info_modifiers" => "Modifikatoren",
			"info_rewards" => "Mögliche Belohnungen",
			"info_completed" => "Fertiggestellt",
			"info_completed_b" => "",
			"info_completed_f" => " abgeschlossen",
			"info_completions" => "Fertigstellungen",
			"info_light_twenty" => "Du musst Level 20 sein, um Licht zu erhalten.",
			"info_no_pvp" => "Sie müssen am Schmelztiegel mindestens einmal teilnehmen, um Medaillen zu erhalten.",
			"time_played" => "Spielzeit ",
			"time_played_f" => "",
			"time_active" => "Activ",
			"time_minute" => "Min. ",
			"time_hour" => "Std. ",
			"time_day" => "T. ",
			"button_share" => "Teilen",
			"button_permalink" => "Permalink",
			"button_reload" => "Nachladen",
			"button_characters" => "Hüter",
			"button_grimoire" => "Grimoire",
			"button_collection" => "Collection",
			"menu_overview" => "Hüter",
			"menu_weekly" => "Periodisch",
			"menu_equipment" => "Ausrüstung",
			"menu_progression" => "Fortschritt",
			"menu_statistics" => "Statistik",
			"menu_medals" => "Medaillen",
			"menu_all" => "Alle",
			"menu_story" => "Story",
			"menu_patrol" => "Patrouille",
			"menu_strikes" => "Strike",
			"menu_crucible" => "Schmelztiegel",
			"menu_raid" => "Raid",
			"playstation_exclusive" => "Playstation exklusiv",
			"vog_exclusive" => "Gläserne Kammer exklusiv",
			"crota_exclusive" => "Crota's Ende exklusiv",
			"iron_exclusive" => "Eisenbanner exklusiv",
			"character_prestige" => "Licht-Partikel",
			"destination_chests_cosmodrome" => "Erde goldene Truhen",
			"destination_chests_mars" => "Mars goldenen Truhen",
			"destination_chests_moon" => "Mond goldene Truhen",
			"destination_chests_venus" => "Venus goldenen Truhen",
			"faction_cryptarch" => "Kryptoarchäologie",
			"faction_eris" => "Crotas Fluch",
			"faction_event_iron_banner" => "Eisenbanner",
			"faction_event_queen" => "Königin",
			"faction_fotc_vanguard" => "Vorhut-Ruf",
			"faction_pvp" => "Der Schmelztiegel",
			"faction_pvp_dead_orbit" => "Toter Orbit",
			"faction_pvp_future_war_cult" => "Kriegskult Der Zukunft",
			"faction_pvp_new_monarchy" => "Neue Monarchie",
			"pvp_iron_banner.loss_tokens" => "Medaillons des Eisen",
			"pve_coins" => "Vorhut-Marken",
			"pvp_coins" => "Schmelztiegel-Marken",
			"weekly_pve" => "Wöchentlicher Vorhut-Marken",
			"weekly_pvp" => "Wöchentlicher Schmelztiegel-Marken",
			"medal_value" => "Wert",
		),
		"ja" => array(
			"site_name" => "Dinklebot",
			"site_description" => "ガーディアンを追跡と陳列するための個人相手",
			"site_styled_description" => "ガーディアンを<strong>追跡と陳列するため</strong>の<i>個人相手</i>",
			"site_username" => "ユーザー名",
			"site_footer_contact" => "手応えや提案やバグレポートなど場合は、<a href='https://www.facebook.com/dinklebotapp'>Facebook</a>または<a href='http://redd.it/33aizq'>Reddit</a>に私達を連絡ください。",
			"site_footer_mention" => "はBungieと連関していません。",
			"site_footer_language" => "言語",
			"site_thankyou" => "ありがとうございました!",
			"site_thankyou_f" => "寄付はすべて大切です。",
			"category_exotic_armor" => "エキゾチックの甲冑",
			"category_exotic_weapons" => "エキゾチックの武器",
			"category_vog_armor" => "ガラスの間の甲冑",
			"category_vog_weapons" => "ガラスの間の武器",
			"category_vog_misc" => "ガラスの間のアイテム",
			"category_crota_armor" => "クロタの最期の甲冑",
			"category_crota_weapons" => "クロタの最期の武器",
			"category_crota_misc" => "クロタの最期のアイテム",
			"category_ironbanner_armor" => "アイアンバナーの甲冑",
			"category_ironbanner_weapons" => "アイアンバナーの武器",
			"category_ironbanner_misc" => "アイアンバナーのアイテム",
			"info_obtained" => "手に入れた",
			"info_refresh" => "そこの情報は、毎時更新します。",
			"info_ends" => "",
			"info_ends_f" => "で終了",
			"info_modifiers" => "修飾子",
			"info_rewards" => "リワード",
			"info_completed" => "完了した",
			"info_completed_b" => "",
			"info_completed_f" => "で完了",
			"info_completions" => "補完",
			"info_light_twenty" => "ライトを得るためにレベル2なければなりません。",
			"info_no_pvp" => "メダルを得るためにクルーシブルを参加なければいけません。",
			"time_played" => "",
			"time_played_f" => "プレイした",
			"time_active" => "アクティブ",
			"time_minute" => "分",
			"time_hour" => "時間",
			"time_day" => "日",
			"button_share" => "共有",
			"button_permalink" => "パーマリンク",
			"button_reload" => "リロード",
			"button_characters" => "ガーディアン",
			"button_grimoire" => "グリモア",
			"button_collection" => "コレクション",
			"button_show" => "表示",
			"menu_overview" => "ガーディアン",
			"menu_weekly" => "定期的な",
			"menu_equipment" => "装備",
			"menu_progression" => "進捗",
			"menu_statistics" => "統計",
			"menu_medals" => "メダル",
			"menu_all" => "全て",
			"menu_story" => "ストーリー",
			"menu_patrol" => "パトロール",
			"menu_strikes" => "ストライク",
			"menu_crucible" => "クルーシブル",
			"menu_raid" => "レイド",
			"playstation_exclusive" => "Playstationの専属",
			"vog_exclusive" => "ガラスの間の専属",
			"crota_exclusive" => "クロタの最期の専属",
			"iron_exclusive" => "アイアンバナーの専属",
			"character_prestige" => "光のかけら",
			"destination_chests_cosmodrome" => "地球ゴールデンチェスト",
			"destination_chests_mars" => "火星ゴールデンチェスト",
			"destination_chests_moon" => "月ゴールデンチェスト",
			"destination_chests_venus" => "金星ゴールデンチェスト",
			"faction_cryptarch" => "クリプト考古学",
			"faction_eris" => "クロタの破滅",
			"faction_event_iron_banner" => "アイアンバナー",
			"faction_event_queen" => "女王",
			"faction_fotc_vanguard" => "バンガードの評判",
			"faction_pvp" => "クルーシブル",
			"faction_pvp_dead_orbit" => "デッドオービット",
			"faction_pvp_future_war_cult" => "フューチャーウォー・カルト",
			"faction_pvp_new_monarchy" => "ニューモナーキー",
			"pvp_iron_banner.loss_tokens" => "鉄のメダリオン",
			"pve_coins" => "今週のバンガード",
			"pvp_coins" => "今週のクルーシブル",
			"weekly_pve" => "今週のバンガードの紋章",
			"weekly_pvp" => "今週のクルーシブルの紋章",
			"medal_value" => "価値",
		),
		"it" => array(
			"site_name" => "Dinklebot",
			"site_description" => "Il tuo compagno di viaggio per monitorare e mostrare i tuoi Guardiani",
			"site_styled_description" => "Il tuo <i>compagno di viaggio</i> per <strong>monitorare</strong> e <strong>mostrare</strong> i tuoi Guardiani",
			"site_username" => "Nome Utente",
			"site_footer_contact" => "Per feedback, suggerimenti, segnalare un bug o qualsiasi altra cosa relativa al sito, contattaci su <a href='https://www.facebook.com/dinklebotapp'>Facebook</a> o <a href='http://redd.it/33aizq'>Reddit</a>!",
			"site_footer_mention" => "non è in alcun modo affiliato con Bungie.",
			"site_footer_language" => "Lingua",
			"site_thankyou" => "Grazie mille!",
			"site_thankyou_f" => "Sei tu che rendi questo sito fantastico!",
			'category_exotic_armor' => 'Armatura Esotica',
			'category_exotic_weapons' => 'Armi Esotiche',
			'category_vog_armor' => 'Armatura Volta di Vetro',
			'category_vog_weapons' => 'Armi Volta di Vetro',
			'category_vog_misc' => 'Oggetti Volta di Vetro',
			'category_crota_armor' => 'Armatura Fine di Crota',
			'category_crota_weapons' => 'Armi Fine di Crota',
			'category_crota_misc' => 'Oggetti Fine di Crota',
			'category_ironbanner_armor' => 'Armatura Stendardo di Ferro',
			'category_ironbanner_weapons' => 'Armi Stendardo di Ferro',
			'category_ironbanner_misc' => 'Oggetti Stendardo di Ferro',
			'info_obtained' => 'Ottenuto',
			'info_completed_b' => 'Completato ',
			'info_completed_f' => '',
			"info_refresh" => "Quest'informazione si aggiorna ogni ora.",
			"info_ends" => "Finisce tra ",
			"info_ends_f" => "",
			"info_modifiers" => "Modificatori",
			"info_rewards" => "Ricompense Possibili",
			"info_completed" => "Completato",
			"info_completions" => "Completamenti",
			"info_light_twenty" => "Devi essere al livello 20 per ottenere Luce.",
			"info_no_pvp" => "Devi partecipare ad almeno una partita nel Crogiolo per ottenere medaglie.",
			"time_played" => "Tempo di Gioco ",
			"time_played_f" => "",
			"time_active" => "Attivo",
			"time_minute" => "m ",
			"time_hour" => "o ",
			"time_day" => "g ",
			"button_share" => "Condividi",
			"button_permalink" => "Permalink",
			"button_reload" => "Aggiorna",
			'button_characters' => 'Guardiani',
			'button_grimoire' => 'Grimorio',
			'button_collection' => 'Collezione',
			"menu_overview" => "Riepilogo",
			"menu_weekly" => "Periodico",
			"menu_equipment" => "Equipaggiamento",
			"menu_progression" => "Progresso",
			"menu_statistics" => "Statistiche",
			"menu_medals" => "Medaglie",
			"menu_all" => "Tutto",
			"menu_story" => "Storia",
			"menu_patrol" => "Pattuglia",
			"menu_strikes" => "Assalto",
			"menu_crucible" => "Crogiolo",
			"menu_raid" => "Incursione",
			"playstation_exclusive" => "Esclusiva Playstation",
			"vog_exclusive" => "Esclusiva Volta di Vetro",
			"crota_exclusive" => "Esclusiva Fine di Crota",
			"iron_exclusive" => "Esclusiva Stendardo di Ferro",
			"character_prestige" => "Particella di Luce",
			"destination_chests_cosmodrome" => "Terra: Forzieri d'oro",
			"destination_chests_mars" => "Marte: Forzieri d'oro",
			"destination_chests_moon" => "Luna: Forzieri d'oro",
			"destination_chests_venus" => "Venere: Forzieri d'oro",
			"faction_cryptarch" => "Criptoarcheologia",
			"faction_eris" => "Sventura di Crota",
			"faction_event_iron_banner" => "Stendardo di Ferro",
			"faction_event_queen" => "Regina",
			"faction_fotc_vanguard" => "Reputazione Avanguardia",
			"faction_pvp" => "Crogiolo",
			"faction_pvp_dead_orbit" => "Orbita Morta",
			"faction_pvp_future_war_cult" => "Culto Guerra Futura",
			"faction_pvp_new_monarchy" => "Nuova Monarchia",
			"pvp_iron_banner.loss_tokens" => "Medaglioni di ferro",
			"pve_coins" => "Marchi dell'Avanguardia",
			"pvp_coins" => "Marchi del Crogiolo",
			"weekly_pve" => "Marchi dell'Avanguardia Settimanali",
			"weekly_pvp" => "Marchi del Crogiolo Settimanali",
			"medal_value" => "Quantità",
		),
	);

}